import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class={styles.homeContainer}>
        <div class={styles.overlay}></div>
        <div class={styles.mainGrid}></div>
        <div class={styles.movingGrid}></div>
        <div class={styles.inviteContainer}>
          sup
        </div>
      </div>
    </>
  )
}
